### ISSUE TITLE
This Zone is banned

### ISSUE THREAD

**Issue by vjex** [mandatoryprogrammer/cloudflare_enum#1]
After running script.
The result is showing :

`{"success":false,"errors":[{"code":1097,"message":"This zone is banned and cannot be added to CloudFlare at this time, please contact CloudFlare Support."}],"messages":[],"result":null}`

**Comment by mandatoryprogrammer** [comment]
Please provide the domain name you tried, Cloudflare bans certain domains from being imported.

**Comment by vjex** [comment]
I tried disney.com

**Comment by mandatoryprogrammer** [comment]
This message is only returned for Disney.com correct? Other non-popular domains work just fine?

**Comment by vjex** [comment]
No, I tried couple of other also.

Same issue.

**Comment by mandatoryprogrammer** [comment]
Hmm script appears to be broken, will have to investigate and issue a patch.

**Comment by phwd** [comment]
The script seems fine now. Using cloudfare.com shows the same issues. Tried the following just for curiosity

* twitter.com
* facebook.com
* instagram.com
* fb.com

Seems like Cloudfare is blacklisting some domains not all though
![ee](https://cloud.githubusercontent.com/assets/402933/20926006/94475fae-bb90-11e6-8d45-d96ed70fedec.png)

**Comment by mandatoryprogrammer** [comment]
Ah yes this was fixed with an earlier update but I forgot to close this issue!
